-- ============================================================================
-- Dolphin Memory — Supabase Schema
-- ============================================================================
-- Run this in your Supabase SQL Editor to set up the required tables.
-- ============================================================================

-- Enable vector extension
CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "public";

-- ============================================================================
-- TABLE: user_memories (Semantic memory store)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.user_memories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL,
    memory_type text,
    content jsonb,
    confidence double precision DEFAULT 1.0,
    last_accessed timestamp without time zone,
    embedding public.vector(768),
    status text DEFAULT 'active',
    created_at timestamp with time zone DEFAULT now()
);

-- ============================================================================
-- TABLE: graph_nodes (Knowledge Graph nodes)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.graph_nodes (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id text NOT NULL,
    name text NOT NULL,
    label text NOT NULL,
    embedding public.vector(768),
    access_count integer DEFAULT 0,
    decay_score double precision DEFAULT 1.0,
    last_accessed timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE (session_id, name)
);

-- ============================================================================
-- TABLE: graph_edges (Knowledge Graph relationships)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.graph_edges (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id text NOT NULL,
    source_id uuid REFERENCES public.graph_nodes(id) ON DELETE CASCADE,
    target_id uuid REFERENCES public.graph_nodes(id) ON DELETE CASCADE,
    relationship text NOT NULL,
    weight double precision DEFAULT 1.0,
    last_accessed timestamp with time zone DEFAULT now(),
    access_count integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE (source_id, target_id, relationship)
);

-- ============================================================================
-- TABLE: conversation_logs (Optional — for chat apps using Dolphin server)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.conversation_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    embedding public.vector(768),
    created_at timestamp with time zone DEFAULT timezone('utc', now())
);

-- ============================================================================
-- INDEXES
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_graph_edges_source ON graph_edges(source_id);
CREATE INDEX IF NOT EXISTS idx_graph_edges_target ON graph_edges(target_id);
CREATE INDEX IF NOT EXISTS idx_graph_edges_session ON graph_edges(session_id);
CREATE INDEX IF NOT EXISTS idx_graph_nodes_session ON graph_nodes(session_id);
CREATE INDEX IF NOT EXISTS idx_conversation_logs_session ON conversation_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_user_memories_session ON user_memories(session_id);

-- ============================================================================
-- FUNCTION: match_memories (Vector similarity search)
-- ============================================================================
CREATE OR REPLACE FUNCTION public.match_memories(
    query_embedding public.vector,
    match_threshold double precision,
    match_count integer,
    p_session_id text
)
RETURNS TABLE(
    id bigint,
    memory_type text,
    content jsonb,
    created_at timestamp with time zone,
    similarity double precision
)
LANGUAGE plpgsql AS $function$
BEGIN
    RETURN QUERY
    SELECT
        user_memories.id,
        user_memories.memory_type,
        user_memories.content,
        user_memories.created_at,
        1 - (user_memories.embedding <=> query_embedding) AS similarity
    FROM user_memories
    WHERE 1 - (user_memories.embedding <=> query_embedding) > match_threshold
    AND user_memories.session_id = p_session_id
    AND user_memories.status = 'active'
    ORDER BY user_memories.embedding <=> query_embedding
    LIMIT match_count;
END;
$function$;

-- ============================================================================
-- FUNCTION: match_graph_nodes (Find relevant nodes by embedding)
-- ============================================================================
CREATE OR REPLACE FUNCTION public.match_graph_nodes(
    query_embedding public.vector,
    match_threshold double precision,
    match_count integer,
    p_session_id text
)
RETURNS TABLE(
    id uuid,
    name text,
    label text,
    similarity double precision
)
LANGUAGE plpgsql AS $function$
BEGIN
    RETURN QUERY
    SELECT
        graph_nodes.id,
        graph_nodes.name,
        graph_nodes.label,
        1 - (graph_nodes.embedding <=> query_embedding) AS similarity
    FROM graph_nodes
    WHERE 1 - (graph_nodes.embedding <=> query_embedding) > match_threshold
    AND graph_nodes.session_id = p_session_id
    ORDER BY graph_nodes.embedding <=> query_embedding
    LIMIT match_count;
END;
$function$;
