drop extension if exists "pg_net";

create extension if not exists "vector" with schema "public";


  create table "public"."conversation_logs" (
    "id" bigint generated by default as identity not null,
    "session_id" text not null,
    "role" text not null,
    "content" text not null,
    "embedding" public.vector(768),
    "created_at" timestamp with time zone default timezone('utc'::text, now())
      );



  create table "public"."graph_edges" (
    "id" uuid not null default gen_random_uuid(),
    "session_id" text not null,
    "source_id" uuid,
    "target_id" uuid,
    "relationship" text not null,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."graph_nodes" (
    "id" uuid not null default gen_random_uuid(),
    "session_id" text not null,
    "name" text not null,
    "label" text not null,
    "embedding" public.vector(768),
    "created_at" timestamp with time zone default now()
      );



  create table "public"."user_memories" (
    "id" bigint generated by default as identity not null,
    "session_id" text not null,
    "memory_type" text,
    "content" jsonb,
    "confidence" double precision,
    "last_accessed" timestamp without time zone,
    "embedding" public.vector(768),
    "status" text default 'active'::text,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."user_tasks" (
    "id" uuid not null default gen_random_uuid(),
    "session_id" text not null,
    "description" text not null,
    "status" text default 'pending'::text,
    "priority" text default 'medium'::text,
    "due_date" timestamp with time zone,
    "created_at" timestamp with time zone default now()
      );


CREATE UNIQUE INDEX conversation_logs_pkey ON public.conversation_logs USING btree (id);

CREATE UNIQUE INDEX graph_edges_pkey ON public.graph_edges USING btree (id);

CREATE UNIQUE INDEX graph_nodes_pkey ON public.graph_nodes USING btree (id);

CREATE UNIQUE INDEX graph_nodes_session_id_name_key ON public.graph_nodes USING btree (session_id, name);

CREATE INDEX idx_pending_tasks ON public.user_tasks USING btree (session_id, status);

CREATE UNIQUE INDEX user_memories_pkey ON public.user_memories USING btree (id);

CREATE UNIQUE INDEX user_tasks_pkey ON public.user_tasks USING btree (id);

alter table "public"."conversation_logs" add constraint "conversation_logs_pkey" PRIMARY KEY using index "conversation_logs_pkey";

alter table "public"."graph_edges" add constraint "graph_edges_pkey" PRIMARY KEY using index "graph_edges_pkey";

alter table "public"."graph_nodes" add constraint "graph_nodes_pkey" PRIMARY KEY using index "graph_nodes_pkey";

alter table "public"."user_memories" add constraint "user_memories_pkey" PRIMARY KEY using index "user_memories_pkey";

alter table "public"."user_tasks" add constraint "user_tasks_pkey" PRIMARY KEY using index "user_tasks_pkey";

alter table "public"."graph_edges" add constraint "graph_edges_source_id_fkey" FOREIGN KEY (source_id) REFERENCES public.graph_nodes(id) ON DELETE CASCADE not valid;

alter table "public"."graph_edges" validate constraint "graph_edges_source_id_fkey";

alter table "public"."graph_edges" add constraint "graph_edges_target_id_fkey" FOREIGN KEY (target_id) REFERENCES public.graph_nodes(id) not valid;

alter table "public"."graph_edges" validate constraint "graph_edges_target_id_fkey";

alter table "public"."graph_nodes" add constraint "graph_nodes_session_id_name_key" UNIQUE using index "graph_nodes_session_id_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_multi_hop_context(p_session_id text, p_max_nodes integer DEFAULT 15)
 RETURNS TABLE(source_name text, relationship text, target_name text, target_label text, hop_level integer)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  WITH RECURSIVE graph_path AS (
    -- Step 1: Find the User node (Root)
    SELECT 
      id, 
      name as current_name, 
      NULL::text as rel, 
      NULL::text as prev_name, 
      0 as level
    FROM graph_nodes
    WHERE session_id = p_session_id AND name = 'User'

    UNION ALL

    -- Step 2: Traverse to 1-hop and 2-hop connections
    SELECT 
      gn.id, 
      gn.name, 
      ge.relationship, 
      gp.current_name, 
      gp.level + 1
    FROM graph_edges ge
    JOIN graph_nodes gn ON ge.target_id = gn.id
    JOIN graph_path gp ON ge.source_id = gp.id
    WHERE gp.level < 2 -- Discovery Depth
    AND ge.session_id = p_session_id
  )
  SELECT 
    prev_name, 
    rel, 
    current_name, 
    (SELECT label FROM graph_nodes WHERE id = graph_path.id), 
    level
  FROM graph_path
  WHERE level > 0
  LIMIT p_max_nodes;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.match_conversation(query_embedding public.vector, match_threshold double precision, match_count integer, p_session_id text)
 RETURNS TABLE(id bigint, content text, similarity double precision)
 LANGUAGE plpgsql
AS $function$
begin
  return query
  select
    conversation_logs.id,
    conversation_logs.content,
    1 - (conversation_logs.embedding <=> query_embedding) as similarity
  from conversation_logs
  where 1 - (conversation_logs.embedding <=> query_embedding) > match_threshold
  and session_id = p_session_id
  order by conversation_logs.embedding <=> query_embedding
  limit match_count;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.match_graph_nodes(query_embedding public.vector, match_threshold double precision, match_count integer, p_session_id text)
 RETURNS TABLE(name text, label text, similarity double precision)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    graph_nodes.name,
    graph_nodes.label,
    1 - (graph_nodes.embedding <=> query_embedding) AS similarity
  FROM graph_nodes
  WHERE 1 - (graph_nodes.embedding <=> query_embedding) > match_threshold
  AND graph_nodes.session_id = p_session_id
  ORDER BY graph_nodes.embedding <=> query_embedding
  LIMIT match_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.match_memories(query_embedding public.vector, match_threshold double precision, match_count integer, p_session_id text)
 RETURNS TABLE(id bigint, memory_type text, content jsonb, created_at timestamp with time zone, similarity double precision)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    user_memories.id,
    user_memories.memory_type,
    user_memories.content,
    user_memories.created_at,
    1 - (user_memories.embedding <=> query_embedding) AS similarity
  FROM user_memories
  WHERE 1 - (user_memories.embedding <=> query_embedding) > match_threshold
  AND user_memories.session_id = p_session_id
  ORDER BY user_memories.embedding <=> query_embedding
  LIMIT match_count;
END;
$function$
;

grant delete on table "public"."conversation_logs" to "anon";

grant insert on table "public"."conversation_logs" to "anon";

grant references on table "public"."conversation_logs" to "anon";

grant select on table "public"."conversation_logs" to "anon";

grant trigger on table "public"."conversation_logs" to "anon";

grant truncate on table "public"."conversation_logs" to "anon";

grant update on table "public"."conversation_logs" to "anon";

grant delete on table "public"."conversation_logs" to "authenticated";

grant insert on table "public"."conversation_logs" to "authenticated";

grant references on table "public"."conversation_logs" to "authenticated";

grant select on table "public"."conversation_logs" to "authenticated";

grant trigger on table "public"."conversation_logs" to "authenticated";

grant truncate on table "public"."conversation_logs" to "authenticated";

grant update on table "public"."conversation_logs" to "authenticated";

grant delete on table "public"."conversation_logs" to "service_role";

grant insert on table "public"."conversation_logs" to "service_role";

grant references on table "public"."conversation_logs" to "service_role";

grant select on table "public"."conversation_logs" to "service_role";

grant trigger on table "public"."conversation_logs" to "service_role";

grant truncate on table "public"."conversation_logs" to "service_role";

grant update on table "public"."conversation_logs" to "service_role";

grant delete on table "public"."graph_edges" to "anon";

grant insert on table "public"."graph_edges" to "anon";

grant references on table "public"."graph_edges" to "anon";

grant select on table "public"."graph_edges" to "anon";

grant trigger on table "public"."graph_edges" to "anon";

grant truncate on table "public"."graph_edges" to "anon";

grant update on table "public"."graph_edges" to "anon";

grant delete on table "public"."graph_edges" to "authenticated";

grant insert on table "public"."graph_edges" to "authenticated";

grant references on table "public"."graph_edges" to "authenticated";

grant select on table "public"."graph_edges" to "authenticated";

grant trigger on table "public"."graph_edges" to "authenticated";

grant truncate on table "public"."graph_edges" to "authenticated";

grant update on table "public"."graph_edges" to "authenticated";

grant delete on table "public"."graph_edges" to "service_role";

grant insert on table "public"."graph_edges" to "service_role";

grant references on table "public"."graph_edges" to "service_role";

grant select on table "public"."graph_edges" to "service_role";

grant trigger on table "public"."graph_edges" to "service_role";

grant truncate on table "public"."graph_edges" to "service_role";

grant update on table "public"."graph_edges" to "service_role";

grant delete on table "public"."graph_nodes" to "anon";

grant insert on table "public"."graph_nodes" to "anon";

grant references on table "public"."graph_nodes" to "anon";

grant select on table "public"."graph_nodes" to "anon";

grant trigger on table "public"."graph_nodes" to "anon";

grant truncate on table "public"."graph_nodes" to "anon";

grant update on table "public"."graph_nodes" to "anon";

grant delete on table "public"."graph_nodes" to "authenticated";

grant insert on table "public"."graph_nodes" to "authenticated";

grant references on table "public"."graph_nodes" to "authenticated";

grant select on table "public"."graph_nodes" to "authenticated";

grant trigger on table "public"."graph_nodes" to "authenticated";

grant truncate on table "public"."graph_nodes" to "authenticated";

grant update on table "public"."graph_nodes" to "authenticated";

grant delete on table "public"."graph_nodes" to "service_role";

grant insert on table "public"."graph_nodes" to "service_role";

grant references on table "public"."graph_nodes" to "service_role";

grant select on table "public"."graph_nodes" to "service_role";

grant trigger on table "public"."graph_nodes" to "service_role";

grant truncate on table "public"."graph_nodes" to "service_role";

grant update on table "public"."graph_nodes" to "service_role";

grant delete on table "public"."user_memories" to "anon";

grant insert on table "public"."user_memories" to "anon";

grant references on table "public"."user_memories" to "anon";

grant select on table "public"."user_memories" to "anon";

grant trigger on table "public"."user_memories" to "anon";

grant truncate on table "public"."user_memories" to "anon";

grant update on table "public"."user_memories" to "anon";

grant delete on table "public"."user_memories" to "authenticated";

grant insert on table "public"."user_memories" to "authenticated";

grant references on table "public"."user_memories" to "authenticated";

grant select on table "public"."user_memories" to "authenticated";

grant trigger on table "public"."user_memories" to "authenticated";

grant truncate on table "public"."user_memories" to "authenticated";

grant update on table "public"."user_memories" to "authenticated";

grant delete on table "public"."user_memories" to "service_role";

grant insert on table "public"."user_memories" to "service_role";

grant references on table "public"."user_memories" to "service_role";

grant select on table "public"."user_memories" to "service_role";

grant trigger on table "public"."user_memories" to "service_role";

grant truncate on table "public"."user_memories" to "service_role";

grant update on table "public"."user_memories" to "service_role";

grant delete on table "public"."user_tasks" to "anon";

grant insert on table "public"."user_tasks" to "anon";

grant references on table "public"."user_tasks" to "anon";

grant select on table "public"."user_tasks" to "anon";

grant trigger on table "public"."user_tasks" to "anon";

grant truncate on table "public"."user_tasks" to "anon";

grant update on table "public"."user_tasks" to "anon";

grant delete on table "public"."user_tasks" to "authenticated";

grant insert on table "public"."user_tasks" to "authenticated";

grant references on table "public"."user_tasks" to "authenticated";

grant select on table "public"."user_tasks" to "authenticated";

grant trigger on table "public"."user_tasks" to "authenticated";

grant truncate on table "public"."user_tasks" to "authenticated";

grant update on table "public"."user_tasks" to "authenticated";

grant delete on table "public"."user_tasks" to "service_role";

grant insert on table "public"."user_tasks" to "service_role";

grant references on table "public"."user_tasks" to "service_role";

grant select on table "public"."user_tasks" to "service_role";

grant trigger on table "public"."user_tasks" to "service_role";

grant truncate on table "public"."user_tasks" to "service_role";

grant update on table "public"."user_tasks" to "service_role";


